### ISSUE TITLE
How to tell DaSpec step to carry on

### ISSUE THREAD

**Issue by philipbeadle** [daspec/daspec-js-npm#2]
Hi 
In Cucumber.js you can either return a promise from a step or directly call the call back.  this allows you to make sure the step has completed before the next one is executed.  How do we do that in DaSpec? 
I ask because now that I have it working as a protractor framework I now cannot get DaSpec to wait for the page to load.
Doing this
```defineStep(/Navigate to "(.*)"/, function (expectedGreeting) {
  browser.get('http://localhost:9099/').then(function(){
    expect('Home').toEqual(expectedGreeting);
  });
});```

Loads the page but the step carries on before its loaded thus not executing the assertion and the browser quits before the page loads.

**Comment by saufpompiers** [comment]
Hi,

Promises are not supported yet in 1.0. We left it so that it's technically relatively easy to do them, but didn't want to rush ahead until the first real use case. So if I understand correctly, you need to wait until a promise resolves so that you can then execute the assertions? If so, would something like this work:

var promise = browser.get('http://localhost:9099/');
expect(promise).toResolveWith(function (result) {
  expect(result.code).toEqual(...); // assertions on the promise result
  expect('Home').toEqual(expectedGreeting); // assertions on other objects
});

**Comment by philipbeadle** [comment]
The problem is that the step finishes before the promise.
```defineStep(/Navigate to "(.*)"/, function (expectedGreeting) {
  var promise = browser.get('http://google.com/');
  expect(promise).toResolveWith(function (result) {
    console.log('test');
  });
});```
never prints the 'test' to the console.  WebDriver.io and Cucumber.js and Chimp.js allow the developer to control when the step is "Done" by returning the promise or directly calling the callback.  Without that feature you cant test a browser :)
Glad to hear its in the pipeline.

**Comment by gojko** [comment]
I would change the step processing to wait for any promises that get `toResolveWith()` expectations if the syntax looks OK

**Comment by philipbeadle** [comment]
exactly what I want to do, how would i do that?

**Comment by gojko** [comment]
That's probably better if I do it, because I'd need to change how the runner behaves. I'll try to do it over the weekend.

**Comment by gojko** [comment]
daspec 1.1.0 now supports promises. I've done it so that if a step definition returns a promise, the runner will wait for it to finish. At the end, I've not implemented the `toResolveWith` matcher because it wasn't needed, you can just wait for a promise to resolve in the step and do normal expectations in the `then` handler.


So if you try this 

    defineStep(/Navigate to "(.*)"/, function (expectedGreeting) {
      return browser.get('http://localhost:9099/').then(function(){ 
         expect('Home').toEqual(expectedGreeting); 
      }); 
    });

the runner should wait for the promise to complete. (notice the `return` at the start, which sends the promise out of the step)

**Comment by philipbeadle** [comment]
Thats awesome Ill try it out.

**Comment by gojko** [comment]
here's an example: http://daspec.com/examples/advanced/async_promises/
